### PR TITLE
Revert remove gatk call

### PR DESCRIPTION
**Pull request by HenziKou**

### CODE REVIEW

**Comment by mchenaux** [comment]
I think there's a problem, doesn't look like the .dict or .fai are being written
Screenshot 2024-02-09 at 1 44 57 PM

**Comment by HenziKou** [comment]
> I think there's a problem, doesn't look like the .dict or .fai are being written Screenshot 2024-02-09 at 1 44 57 PM

It's working for me. I get the 3 different output files 
image
. Did you update your local `q2-types-variant` install after you merged my new PR for that repo?

**Comment by mchenaux** [comment]
@HenziKou Yes, I updated all of the branches before testing.  That's strange... These are the correct branches, right?
Screenshot 2024-02-09 at 2 32 16 PM

**Comment by mchenaux** [comment]
Wait, in your directory, are the .fasta, .fasta.fai, and .dict written outside of the .qza?

**Comment by HenziKou** [comment]
I'm using the `main` branch in `q2-types-variant` and `revert-remove-gatk-call` in `q2-samtools`. The .qza is the result file from running `q2-samtools.index_sequences()` and then I just export the file in the same directory.

**Comment by mchenaux** [comment]
Ok, this works for me if I'm on main for types-variant and revert-create-sequence-dictionary for gatk.

**Review by mchenaux — APPROVED** [review]

**Pull request merged**
